version: "3"

services:
  web:
    image: php:7.4-apache
    container_name: php-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./vendor:/var/www/vendor

  mysql:
    image: mysql:5.7
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: cnpm
      MYSQL_USER: nguyenhien
      MYSQL_PASSWORD: "root"
    volumes:
      - ./mysql-data:/var/lib/mysql
